config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'dictionary/index'
  resources :dictionary, only: [:index, :show, :create]
  resources :words, only: [:index, :show]

  post '/set_active_language', action: :set_active_language, controller: :active_language

  namespace :admin do
    resources :languages
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root action: :index, controller: :dictionary
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/definition.rb
class Definition < ApplicationRecord
  belongs_to :word
  belongs_to :language
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :definitions
  has_many :part_of_speeches

  validates_presence_of :name
end

app/models/part_of_speech.rb
class PartOfSpeech < ApplicationRecord
  belongs_to :language
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :definitions
end

app/controllers/active_language_controller.rb
class ActiveLanguageController < ApplicationController

  def set_active_language
    if Language.find_by_id(params[:active_language_id]) != nil
      cookies[:active_language_id] = params[:active_language_id]
    else
      redirect_to root_path, status: :unprocessable_entity
    end
  end
end

app/controllers/admin/languages_controller.rb
class Admin::LanguagesController < ApplicationController

  def index
    @languages = Language.all
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      flash[:notice] = "Language successfully created."
      redirect_to admin_languages_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @language = Language.find_by_id(params[:id])
  end

  def update
    @language = Language.find_by_id(params[:id])
    if @language.update(language_params)
      flash[:notice] = "Language successfully updated."
      redirect_to admin_languages_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @language = Language.find_by_id(params[:id])
    if @language.destroy
      flash[:notice] = "Language successfully deleted."
      redirect_to admin_languages_path
    else
      render :index, status: :not_modified
    end
  end

  private
  def language_params 
    params.require(:language).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dictionary_controller.rb
class DictionaryController < ApplicationController
  def index
    @parts_of_speech = PartOfSpeech.all
    @words = Word.all
  end

  def show
    @letter = params[:id]
    @words = Word.where('substr(word, 1, 1) = ?', @letter)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.all
  end

  def show
    @word = Word.find_by_id(params[:id])
  end
end

app/helpers/active_language_helper.rb
module ActiveLanguageHelper

  def active_language_select_tag
    languages = Language.all.to_a.delete_if {|language| language.name == "English" }
    options = options_from_collection_for_select(languages, "id", "name", cookies[:active_language_id] || 1)
    select_tag "active_language_id", options, { id: "active_language_select_tag" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionary_helper.rb
module DictionaryHelper
  LETTERS = ['i', 'u', 'e', 'o', 'a', 'm', 'n', 'p', 't', 'k', 's', 'w', 'l', 'j'].sort

  def alphabetical_links(letter = nil)

    LETTERS.map do |l|
      if l == letter then
          "<p class=\"selected-letter\">#{l.to_s}</p>"
      else
        link_to l.to_s, dictionary_path(l)#, class: "dictionary_index_links text-center"
      end
    end.join("\n")
  end
end

app/helpers/language_helper.rb
module LanguageHelper
end

app/helpers/word_helper.rb
module WordHelper
end

app/views/admin/languages/_errors.html.erb
<% if language.errors.any? %>
  <% language.errors.full_messages.each do |message| %>
    <h6><%= message %></h6>
  <% end %>
<% end %>

app/views/admin/languages/_form.html.erb
<%= form_for [:admin, language] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <br/>
  <%= f.submit %>
<% end %>

app/views/admin/languages/create.html.erb
<h1>Language#create</h1>
<p>Find me in app/views/language/create.html.erb</p>

app/views/admin/languages/destroy.html.erb
<h1>Language#destroy</h1>
<p>Find me in app/views/language/destroy.html.erb</p>

app/views/admin/languages/edit.html.erb
<%= render "admin/languages/errors", language: @language %>

<h1>Edit Language</h1>

<%= render "admin/languages/form", language: @language %>

app/views/admin/languages/index.html.erb
<h1>Languages</h1>

<table>
<tr>
  <td><b>Language</b></td>
</tr>
<% @languages.each do |language| %>
  <tr>
    <td><%= language.name %></td>
    <td><%= link_to "Edit", edit_admin_language_path(language) %></td>
    <td> | </td>
    <td><%= link_to "Delete", admin_language_path(language), data: { turbo_method: :delete,
                                                               turbo_confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br/>
<br/>
<%= link_to "New Language", new_admin_language_path %>

app/views/admin/languages/new.html.erb
<%= render "admin/languages/errors", language: @language %>

<h1>New Language</h1>

<%= render "admin/languages/form", language: @language %>

app/views/admin/languages/show.html.erb
<h1>Language#show</h1>
<p>Find me in app/views/language/show.html.erb</p>

app/views/admin/languages/update.html.erb
<h1>Language#update</h1>
<p>Find me in app/views/language/update.html.erb</p>

app/views/application/_alphabetical_links.html.erb
<hr>
<div class="text-center mx-1 dictionary-index-links">
  «
  <% unless defined?(letter) %>
    <%= sanitize alphabetical_links, tags: ["a", "div", "p"] %>
  <% else %>
    <%= sanitize alphabetical_links(letter), tags: ["a", "div", "p"] %>
  <% end %>
  »
</div>
<hr>

app/views/application/_definitions.html.erb
<table>
  <tr>
    <td><b>Part of Speech</b></td>
    <td><b>Definition</b></td>
  </tr>
<% word.definitions.each do |definition| %>
  <tr>
    <td><b><%= definition.pos %></b></td>
    <td><%= definition.definition %></td>
  </tr>
<% end %>
</table>

app/views/application/_partsofspeech.html.erb
<h1>Parts of Speech</h1>

<table>
  <tr>
    <td><b>Part of Speech</b></td>
    <td><b>Definition</b></td>
  </tr>
<% parts_of_speech.each do |item| %>
  <tr>
    <td><b><%= item.pos %></b></td>
    <td><%= item.definition %></td>
  </tr>
<% end %>
</table>

app/views/dictionary/index.html.erb
<h1 class="text-center">Index</h1>
<%= render "alphabetical_links" %>

<div class="p-4">
  <p><%= @parts_of_speech.count %> parts of speech entries in database</p>
  <p><%= @words.count %> word entries in database</p>
</div>

<div class="p-4">
  <%= render "partsofspeech", parts_of_speech: @parts_of_speech %>
</div>

app/views/dictionary/show.html.erb
<div>
  <h1 class="text-center"><b><%= @letter.to_s %></b></h1>
</div>

<%= render "alphabetical_links", letter: @letter %>

<% @words.each do |word| %>
  <div class="dictionary-entry p-4">
    <h2><%= word.word %></h2>
    <%= render "definitions", word: word %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokitranslate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <noscript>
      <style type="text/css">
        #active_language_submit_tag {
          display: inline !important;
        }
      </style>
    </noscript>
  </head>

  <body>
    <div class="container">
      <div class="d-flex mb-3">
        <div class="p-2">
          <%= link_to "Dictionary", dictionary_index_path %>
          <% if user_signed_in? %>
            <pre style="display: inline;">|</pre>
            <%= link_to "Languages", admin_languages_path %>
            <pre style="display: inline;">|</pre>
            <%= form_tag '/set_active_language', class: "d-inline", id: "active_language_form" do %>
              <%= active_language_select_tag %>
              <%= submit_tag "Switch Language", id: "active_language_submit_tag" %>
            <% end %>
          <% end %>
        </div>
        <div class="ms-auto p-2">
          <% if user_signed_in? %>
            <p style="display: inline;">Welcome <%= current_user.username %></p>
            <pre style="display: inline;">|</pre>
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
            <pre style="display: inline;">|</pre>
            <%= link_to "Register", new_user_registration_path %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/words/index.html.erb
<% @words.each do |word| %>
  <p><%= link_to word.word, word %></p>
<% end %>

app/views/words/show.html.erb
<h1><%= @word.word %></h1>

<%= render "definitions", word: @word %>